- name: add key 1
  apt_key:
    keyserver: keys.openpgp.org
    id: "0x0A9AF2115F4687BD29803A206B73A36E6026DFCA"

- name: add key 2
  apt_key:
    url: "{{ item }}"
  with_items:
    - "https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/gpg.E495BB49CC4BBE5B.key"
    - "https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/gpg.9F4587F226208342.key"

- name: add repository
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - "deb https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu focal main"
    - "deb-src https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu focal main"
    - "deb https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu focal main"
    - "deb-src https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu focal main"

- name: install
  apt:
    name: rabbitmq-server
  register: installed

- name: remove user guest
  rabbitmq_user:
    user: guest
    state: absent
  when: installed.changed

- name: add user {{ rabbitmq.username }} / {{ rabbitmq.password }}
  rabbitmq_user:
    user: "{{ rabbitmq.username }}"
    password: "{{ rabbitmq.password }}"
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    tags: administrator
  when: rabbitmq.password != ''

- name: add user {{ rabbitmq.username }}
  rabbitmq_user:
    user: "{{ rabbitmq.username }}"
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    tags: administrator
  when: rabbitmq.password == ''

- name: install rabbitmq plugins
  rabbitmq_plugin:
    name: "{{ item }}"
  with_items: "{{ rabbitmq.plugins }}"

- name: configure rabbitmq
  template:
    src: rabbitmq.conf.j2
    dest: /etc/rabbitmq/rabbitmq.conf
  register: configuration

- name: restart rabbitmq
  systemd:
    name: rabbitmq-server
    state: restarted
  when: configuration.changed
