- name: add apt key for nodejs
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

- name: add apt repository for nodejs
  apt_repository: repo='deb https://deb.nodesource.com/node_{{ nodejs.version }}.x focal main' state=present

- name: install
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - nodejs

- name: Install yarn globally
  npm:
    name: yarn
    global: yes
