- hosts: all
  become: true
  roles:
    - general
    - { role: bash, when: general.config.shell == 'bash' }
    - { role: blackfire, when: role.blackfire }
    - { role: clamav, when: role.clamav }
    - { role: elasticsearch, when: role.elasticsearch }
    - git
    - { role: kafka, when: role.kafka }
    - { role: mariadb, when: role.mariadb }
    - { role: memcached, when: role.memcached }
    - { role: mongodb, when: role.mongodb }
    - { role: nginx, when: role.nginx }
    - { role: nodejs, when: role.nodejs }
    - php
    - { role: postfix, when: role.postfix }
    - { role: postgresql, when: role.postgresql }
    - { role: rabbitmq, when: role.rabbitmq }
    - { role: redis, when: role.redis }
    - { role: zsh, when: general.config.shell == 'zsh' }
    - { role: include_roles }
    - cleanup
